// Strings for the durable validation report: ReportView (paper layout, also
// rendered to static HTML for PDF export), ReportPage (full-page wrapper +
// review controls + export bar), and reportExport (JSON/CSV/PDF labels).
// Keys are namespaced `report.`. Quebec French conventions: "Constats" for
// findings, "Conforme/Non conforme" for pass/fail, proper accents + ’ apostrophes.

export const en = {
  // Header / meta
  'report.eyebrow': 'Validation report',
  'report.title': 'Validation report',
  'report.case': 'Case #{id}',
  'report.runFallback': 'Run #{id}',
  'report.meta.policy': 'Policy',
  'report.meta.version': 'Version',
  'report.meta.documents': 'Documents',
  'report.meta.run': 'Run',
  'report.meta.date': 'Date',

  // Ribbons / state
  'report.ribbon.draft': 'Draft · AI-generated',
  'report.ribbon.finalized': 'Finalized',
  'report.ribbon.finalizedAt': 'Finalized · {date}',
  'report.draft': 'Draft',
  'report.finalized': 'Finalized',

  // Verdict counts
  'report.counts.fail': '{n} fail',
  'report.counts.needReview': '{n} need review',
  'report.counts.pass': '{n} pass',
  'report.counts.na': '{n} n/a',
  'report.reflectsReviewer': 'Reflects reviewer edits',

  // Findings
  'report.findings': 'Findings · {n}',
  'report.noResults': 'No validation results recorded for this run.',
  'report.tag.acrossSet': 'across set',
  'report.tag.anyDoc': 'any doc',
  'report.tag.optional': 'optional',
  'report.documentsCompared': 'Documents compared · {n}',
  'report.perDocument': 'Per document',
  'report.extracted': 'Extracted',

  // Override / note
  'report.ai': 'AI: {status}',
  'report.reviewer': 'Reviewer: {status}',
  'report.reviewedAt': 'Reviewed {date}',
  'report.reviewerNote': 'Reviewer note',

  // Footer
  'report.generatedBy': 'Generated by Clerq2',

  // ReportPage — header / nav
  'report.cases': 'Cases',
  'report.backToCases': 'Back to cases',
  'report.loadingReport': 'Loading report…',
  'report.couldNotLoad': 'Could not load this report.',

  // Export bar
  'report.export.csv': 'CSV',
  'report.export.json': 'JSON',
  'report.export.downloadPdf': 'Download PDF',
  'report.export.reportSuffix': 'Report',
  'report.export.allowPopups': 'Please allow pop-ups to download the PDF.',

  // CSV column headers
  'report.csv.rule_name': 'Rule name',
  'report.csv.scope': 'Scope',
  'report.csv.requirement': 'Requirement',
  'report.csv.ai_status': 'AI verdict',
  'report.csv.effective_status': 'Effective verdict',
  'report.csv.confidence_pct': 'Confidence (%)',
  'report.csv.evidence': 'Evidence',
  'report.csv.reviewer_note': 'Reviewer note',
  'report.csv.reviewer_override_reason': 'Reviewer override reason',
  'report.csv.documents': 'Documents',
  'report.csv.extracted': 'Extracted',

  // Review controls
  'report.verdict': 'Verdict',
  'report.verdict.aiSuffix': '· AI',
  'report.verdict.aiTitle': 'AI verdict — selecting clears your override',
  'report.verdict.overrideTitle': 'Override the AI verdict',
  'report.resetToAi': 'Reset to AI',
  'report.addNote': 'Add note',
  'report.editNote': 'Edit note',
  'report.reasonFor': 'Reason for setting {label} (required)',
  'report.reasonPlaceholder': 'Why are you overriding the AI here?',
  'report.notePlaceholder': 'Add a note for the record…',
  'report.saveOverride': 'Save override',
  'report.saveNote': 'Save note',

  // Sticky action bar
  'report.reportFinalized': 'Report finalized',
  'report.reportFinalizedAt': 'Report finalized · {date}',
  'report.reopenToAmend': 'Reopen to amend',
  'report.reviewPrompt': 'Review the findings — add notes or override a verdict — then finalize.',
  'report.finalizeReport': 'Finalize report',
}

export const fr = {
  // Header / meta
  'report.eyebrow': 'Rapport de validation',
  'report.title': 'Rapport de validation',
  'report.case': 'Dossier no {id}',
  'report.runFallback': 'Exécution no {id}',
  'report.meta.policy': 'Politique',
  'report.meta.version': 'Version',
  'report.meta.documents': 'Documents',
  'report.meta.run': 'Exécution',
  'report.meta.date': 'Date',

  // Ribbons / state
  'report.ribbon.draft': 'Brouillon · généré par l’IA',
  'report.ribbon.finalized': 'Finalisé',
  'report.ribbon.finalizedAt': 'Finalisé · {date}',
  'report.draft': 'Brouillon',
  'report.finalized': 'Finalisé',

  // Verdict counts
  'report.counts.fail': '{n} non conforme(s)',
  'report.counts.needReview': '{n} à réviser',
  'report.counts.pass': '{n} conforme(s)',
  'report.counts.na': '{n} s. o.',
  'report.reflectsReviewer': 'Reflète les modifications du réviseur',

  // Findings
  'report.findings': 'Constats · {n}',
  'report.noResults': 'Aucun résultat de validation enregistré pour cette exécution.',
  'report.tag.acrossSet': 'sur l’ensemble',
  'report.tag.anyDoc': 'tout document',
  'report.tag.optional': 'facultatif',
  'report.documentsCompared': 'Documents comparés · {n}',
  'report.perDocument': 'Par document',
  'report.extracted': 'Extrait',

  // Override / note
  'report.ai': 'IA : {status}',
  'report.reviewer': 'Réviseur : {status}',
  'report.reviewedAt': 'Révisé le {date}',
  'report.reviewerNote': 'Note du réviseur',

  // Footer
  'report.generatedBy': 'Généré par Clerq2',

  // ReportPage — header / nav
  'report.cases': 'Dossiers',
  'report.backToCases': 'Retour aux dossiers',
  'report.loadingReport': 'Chargement du rapport…',
  'report.couldNotLoad': 'Impossible de charger ce rapport.',

  // Export bar
  'report.export.csv': 'CSV',
  'report.export.json': 'JSON',
  'report.export.downloadPdf': 'Télécharger le PDF',
  'report.export.reportSuffix': 'Rapport',
  'report.export.allowPopups': 'Veuillez autoriser les fenêtres contextuelles pour télécharger le PDF.',

  // CSV column headers
  'report.csv.rule_name': 'Nom de la règle',
  'report.csv.scope': 'Portée',
  'report.csv.requirement': 'Exigence',
  'report.csv.ai_status': 'Verdict de l’IA',
  'report.csv.effective_status': 'Verdict effectif',
  'report.csv.confidence_pct': 'Confiance (%)',
  'report.csv.evidence': 'Justification',
  'report.csv.reviewer_note': 'Note du réviseur',
  'report.csv.reviewer_override_reason': 'Motif de dérogation du réviseur',
  'report.csv.documents': 'Documents',
  'report.csv.extracted': 'Extrait',

  // Review controls
  'report.verdict': 'Verdict',
  'report.verdict.aiSuffix': '· IA',
  'report.verdict.aiTitle': 'Verdict de l’IA — le sélectionner annule votre dérogation',
  'report.verdict.overrideTitle': 'Déroger au verdict de l’IA',
  'report.resetToAi': 'Rétablir le verdict de l’IA',
  'report.addNote': 'Ajouter une note',
  'report.editNote': 'Modifier la note',
  'report.reasonFor': 'Motif pour définir {label} (requis)',
  'report.reasonPlaceholder': 'Pourquoi dérogez-vous au verdict de l’IA ici ?',
  'report.notePlaceholder': 'Ajouter une note au dossier…',
  'report.saveOverride': 'Enregistrer la dérogation',
  'report.saveNote': 'Enregistrer la note',

  // Sticky action bar
  'report.reportFinalized': 'Rapport finalisé',
  'report.reportFinalizedAt': 'Rapport finalisé · {date}',
  'report.reopenToAmend': 'Rouvrir pour modifier',
  'report.reviewPrompt': 'Révisez les constats — ajoutez des notes ou dérogez à un verdict — puis finalisez.',
  'report.finalizeReport': 'Finaliser le rapport',
}
